# -*- mode: python ; coding: utf-8 -*-

import os

BASE_DIR = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['main.py'],
    pathex=[BASE_DIR],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('languages', 'languages'),
        ('db_config.json', '.'),
    ],
    hiddenimports=[
        'controllers',
        'controllers.auth_controller',
        'controllers.brand_controller',
        'controllers.category_controller',
        'controllers.customer_controller',
        'controllers.employee_controller',
        'controllers.location_controller',
        'controllers.order_controller',
        'controllers.product_controller',
        'controllers.role_permissions_controller',
        'controllers.stock_controller',
        'controllers.supplier_controller',
        'controllers.variant_type_controller',
        'database',
        'database.base_repository',
        'database.brand_repository',
        'database.category_repository',
        'database.customer_repository',
        'database.database_adapter',
        'database.employee_repository',
        'database.employee_role_repository',
        'database.location_repository',
        'database.order_item_repository',
        'database.order_repository',
        'database.payment_repository',
        'database.permissions_repository',
        'database.product_repository',
        'database.roles_repository',
        'database.stock_movement_repository',
        'database.supplier_repository',
        'database.turso_client',
        'database.user_repository',
        'database.variant_repository',
        'database.variant_type_repository',
        'database.variant_value_repository',
        'models',
        'models.brand_model',
        'models.category_model',
        'models.customer_model',
        'models.employee_model',
        'models.employee_role_model',
        'models.location_model',
        'models.order_item_model',
        'models.order_model',
        'models.payment_model',
        'models.permissions_model',
        'models.product_image_model',
        'models.product_model',
        'models.roles_model',
        'models.stock_movements_model',
        'models.supplier_model',
        'models.user_model',
        'models.variant_model',
        'models.variant_type_model',
        'models.variant_value_model',
        'utils',
        'utils.image_utils',
        'utils.logger',
        'utils.permission_helper',
        'utils.session',
        'utils.theme',
        'utils.translations',
        'views',
        'views.base_dialog',
        'views.base_list_view',
        'views.brands_view',
        'views.categories_view',
        'views.customers_view',
        'views.dashboard_view',
        'views.employees_view',
        'views.locations_view',
        'views.login_view',
        'views.main_window',
        'views.orders_view',
        'views.products_view',
        'views.roles_permissions_view',
        'views.splash_screen',
        'views.stock_view',
        'views.suppliers_view',
        'views.variant_types_view',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='HiandcoTechERP',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=os.path.join(BASE_DIR, 'assets', 'favicon.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='HiandcoTechERP',
)
